stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: image-manager-front
  CONTAINER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CERTIFICATE_DOMAIN: images.maximemoreillon.com

containerization:
  stage: containerization
  script:
      # Docker hub login
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    # Building the container image
    - docker build -t ${CONTAINER_IMAGE} .
    # Pushing the image to the registry
    - docker push ${CONTAINER_IMAGE}
    # Cleanup
    - docker image rm ${CONTAINER_IMAGE}

deployment:
  stage: deployment
  script:
    - envsubst < deployment.yml | kubectl apply -f -
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
